### ISSUE TITLE
This is fascinating vortex visulization, but how you made it?

### ISSUE THREAD

**Issue by randomwangran** [byuflowlab/FLOWUnsteady#1]
5244dab1d573e4072d9913c304eb953640862afd `examples/singlerotor.jl`

It looks like using ParaView.

But how to track the particle and also applied glyphs?

Would you like to share your technique to generate this fascinating video in ParaView?

**Comment by EdoAlvarezR** [comment]
The CFD solver is a Lagrangian (meshless) numerical scheme that, instead of having static elements, the computational elements are the particles that convect with the local velocity as shown in the visualization. This is called vortex particle method (VPM).

Check out some of my publications to learn more about the vortex particle method: https://edoalvarezr.github.io/projects/06-publications.html

**Comment by randomwangran** [comment]
This is master piece. Really beautiful simulations. 

I've downloaded the work you done during the time at Brigham Young University.

I will play with it and try to, possibily, and find experimental data to support your numerical result.
