### ISSUE TITLE
1 dependency errored. To see a full report either run `import Pkg; Pkg.precompile()` or load the package

### ISSUE THREAD

**Issue by inse0918** [byuflowlab/FLOWUnsteady#34]
Hi, i cant precompile FLOWNoise because of this disturbance

First, I tried to add FLOWUnsteady.jl in my julia package.

But he wanted to add pck FLOWVLM.

So i precompiledFLOWVLM but, he wanted to add pck AirfoilPrep.

And then, I precompiled it and this error begining.

Also in FLOWnoise
![image](https://user-images.githubusercontent.com/93040154/162972568-ab21f05d-e83c-44be-8b15-9be4e21e4264.png)
![image](https://user-images.githubusercontent.com/93040154/162972650-b4595c29-dda1-4d4a-8577-0e4004a20c13.png)
Progress doesnt go up.

**Comment by EdoAlvarezR** [comment]
Since FLOWUnsteady has not yet been registered in the official Julia registry, dependencies must by manually satisfied. 
Please follow the installation instructions given in the documentation: [flow.byu.edu/FLOWUnsteady/tutorials/installation-instructions](https://flow.byu.edu/FLOWUnsteady/tutorials/installation-instructions)
